GET http://localhost:3001/

###

POST http://localhost:3001/auth/createUser/ HTTP/1.1
Content-Type: application/json

{
    "ID": "3b52b204-bf91-4e5b-a48a-440245ce663f"
}

###

GET http://localhost:80/auth/getUser?ID=3858c91763e9b205 HTTP/1.1


###

GET http://localhost:3001/auth/getCoupleRegisterID?ID=3b52b204-bf91-4e5b-a48a-440245ce663f HTTP/1.1


###

DELETE http://localhost:3001/auth/deleteUser/ HTTP/1.1
Content-Type: application/json

{
    "ID": "3b52b204-bf91-4e5b-a48a-440245ce663f"
}

###

PATCH http://localhost:80/auth/updatePlayerID/ HTTP/1.1
Content-Type: application/json

{
    "ID": "3858c91763e9b205",
    "playerID": "60e39f0f-d026-49c8-be15-cb21ac656f30"
}

###

PATCH http://localhost:3001/auth/updateCouple/ HTTP/1.1
Content-Type: application/json

{
    "ID": "3b52b204-bf91-4e5b-a48a-440245ce663f",
    "coupleID": "3b52b204-bf91-4e5b-a48a-440245ce663f"
}

###